### ISSUE TITLE
Commercial License

### ISSUE THREAD

**Issue by mayrstefan** [glatzert/ACME-Server-ACDS#2]
Where could we buy a commercial license and what price range should we expect?

**Comment by glatzert** [comment]
I plan to sell a license for a one time fee at 1.500 EUR (+VAT), including all Updates, that will be published here. (all LTS .NET Versions)
The license will include usage in your company for how many servers, domains and certificates you like.
Also it enables you to use either prebuild releases for IIS or Kestrel OR build your own from the source (needs VS currently).

Also I'll ensure you, that if I go out of business, the code will be relicensed as MIT, so further usage is allowed.

If you provide it as a "cloud service" for your customers (let's say more than 1.000 customers), I'd like to take an additional yearly license fee around 750 EUR (+VAT).

I have to set up a store front or find a distribution partner, but I can currently provide a written quote and can also create proper invoices, since I registered a company in Germany.

If you want to get in touch, feel free to contact me via mail.

**Comment by mayrstefan** [comment]
Thank you. I forwarded this information to my colleagues beeing responsible for our MS CA
